- Generally ML model Developed by maths

- convert categorical column to numerical column

- here we are transform the data

- This method is called **Encoding**

- Feature analysis: fst 5 sessions

- Feature Engineering: Transform the data

- Feature selection: Machine learning

  **MODEL DEVELOPMENT**

  
- Before Model development

- we will do EDA : Exploratory data analysis

   - Feature(columns)analysis

      - categorical,Numerical,outlier analysis,bivariate,Multivariate

      - we will get insights

   - Feature engineering

      - we will modify the data

      - Models developed by maths

      - Encoding: Convert categorical data to Numerical Variables

      - Scaling:All the numerical columns makes under one scale

      - Transformations:All the maths developed by assumption data follows normal distribution

          - Convert skewed distribution to Normal


   - Feature selection

- map

- labelEncoder

- one hot Encoder

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
path='visadataset.csv'
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [3]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [4]:
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [5]:
# map the dictionary with column
visa_df['case_status']=visa_df['case_status'].map(d)

In [6]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [7]:
path='visadataset.csv'
visa_df=pd.read_csv(path) 
visa_df['case_status'].unique() 
d={'Certified':0,'Denied':1} 
visa_df['case_status']=visa_df['case_status'].map(d)

In [8]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [9]:
path='visadataset.csv'
visa_df=pd.read_csv(path) 
visa_df['continent'].unique() 
d={'Asia':0,'Africa':1,'North America':2,'Europe':3,'South America':4,'Oceania':5}
visa_df['continent']=visa_df['continent'].map(d)

In [10]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [11]:
path='visadataset.csv'
visa_df=pd.read_csv(path) 
labels=sorted(visa_df['continent'].unique())
# d={}
#for i in range(len(labels)):
 #   key=labels[i]
  #  d[key]=i
d={labels[i]:i for i in range(len(labels))}
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [12]:
path='visadataset.csv' 
visa_df=pd.read_csv(path) 
labels=sorted(visa_df['continent'].unique())
d={labels[i]:i for i in range(len(labels))}
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [13]:
cat=visa_df.select_dtypes(include='object').columns
cat

Index(['case_id', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [14]:
path='visadataset.csv'
visa_df=pd.read_csv(path) 
cat=visa_df.select_dtypes(include='object').columns
for i in cat:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## labelEncoder

- packagename: **sklearn**

   - class: **preprocessing**
                
        -method: **LabelEncoder**

- from sklearn.preprocessing import LabelEncoder

In [15]:
from sklearn.preprocessing import LabelEncoder

- step-1: always import the method

- step-2: save the method

- step-3: apply fit transform

**fit transform**

- fit means : finding something

    - fst we are finding dictionary\

- transform: change the data

    - using the dictionary we are changing Eng to Number

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

In [17]:
from sklearn.preprocessing import LabelEncoder
path='visadataset.csv'
visa_df=pd.read_csv(path) 
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0])

In [18]:
from sklearn.preprocessing import LabelEncoder
path='visadataset.csv'
visa_df=pd.read_csv(path) 
le=LabelEncoder()
for i in cat:
    visa_df[i]=le.fit_transform(visa_df[i]) 
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## **OneHotEncoder**

- The method name is :pd.get_dummies

| case_status | case_status_denied | case_status_Certified |
|-------------|--------------------|-----------------------|
| Denied      | 1                  | 0                     |
| Certified   | 0                  | 1                     |

In [19]:
path='visadataset.csv'
visa_df=pd.read_csv(path)
pd.get_dummies(visa_df['continent'],dtype='int')

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [20]:
visa_df['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

In [24]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [26]:
path='visadataset.csv'
visa_df=pd.read_csv(path)
result=pd.get_dummies(visa_df,columns=cat,dtype='int')
result

,no_of_employees,yr_of_estab,prevailing_wage,case_id_EZYV01,case_id_EZYV02,case_id_EZYV03,case_id_EZYV04,case_id_EZYV05,case_id_EZYV06,case_id_EZYV07,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,1,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,2412,2002,83425.6500,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,44444,2008,122996.8600,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,98,1897,83434.0300,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,1082,2005,149907.3900,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,3274,2006,279174.7900,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,1121,1910,146298.8500,0,0,0,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,1918,1887,86154.7700,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,3195,1960,70876.9100,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

## **LabelEncoder vs OneHotEncoder**

- Generally we dont want a relation between input columns

- we need both input columns are not correlated each other

- we need both input columns are **independent(X,Y)** each other

- we need both input columns are **perpendicular** each other

- we need both input columns are **Orthogonal** each other

- we need both input  columns are **90 degrees phase shift** each other

- OneHotEncoder will achieve above

- But OneHotEncoder creates new columns

   - columns are increases means dimensions are increase

   - more dimension data need more processing time

   - more dimension data need more infra

   - this is called **Curse of Dimensionality**