In [ ]:
====================Data analysis=============================
1. pandas         : Data frame analysis
2. Numpy          : Numerical analysis
3. matplotlib     : Graphs and plots
4. seaborn        : plots
5. Bokhe          : plots
6. ploty          : plots

======================Machine learning=========================
7.stats           : statistical models
8.scikit-learn(sklearn) : ML models

====================== Deep learning==========================
9. opencv         : computer vision
10. pillow        : Image operations
11. tensorflow    : Neural Network creations(developed by google)
12. keras         : NN
13. pytorch       : alternative pckage of tensorflow (facebook meta)

========================NLP===================================
14. NLTK          : Natural language toolkit
15. spacv         : Alternative to NLTK
16. wordcloud     : most frequent occured words

======================scarapping=============================
17. sqLite         :  Database creation
18. Beautiful soup 
19. selenium

======================API creations===========================
20. Flask           
21. FastAPI
22. Gradio
23. Django

=====================UI app creation=========================
24. streamlit

=====================Transer learning Models(DL)=============
25. Mobilenet
26. Resnet
27. VGGnet
28.Inception
29. Yolo  : ultralytics

==================Transfer learning models(NLP)===================
30. word2vec
31. Glove

====================Huging face Transformers=======================

32. BERT :Bi directional Encoder representation of transformers

====================Allen NLP=====================================
33. Allen NLP packages

=======================GenAI========================================
34. langchain
35. Google geminiAi related packages
36. OpenAI GPT related packages
37. Amazon BedRock related packages
38. Meta Llama related packages

========================Image and Video Generations=====================
39. GAN models related packages
40. SORA related packages

============================Model deployment (Mlops)====================
41. mlflow using databricks
42. kubeflow (GCP account)

============================Cloud appilications========================
43. Azure ML related packages
44. GCP vertex AI related  packages
45. AWS sagemaker related packages

==================================small================================
46. time
47. logging
48. math
49. random
50. env
51. os

## **step-1:Import packages**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## **step-2:create a dataframe using list**
   - data:your data either list or dic format

   - index:we need to provide a list

   - columns: we need provide a list

In [2]:
names=['ramesh','suresh','satish']
pd.DataFrame(names)

        0
0  ramesh
1  suresh
2  satish

In [4]:
names=['ramesh','suresh','satish']
pd.DataFrame(names,columns=['Names'])
#pd.dataframe(data,index,columns)

    Names
0  ramesh
1  suresh
2  satish

## **step-3:Change the index**

In [5]:
names=['ramesh','suresh','satish']
idx=['A','B','C']
pd.DataFrame(names,index=idx,columns=['Names'])
#pd.dataframe(data,index,columns)

    Names
A  ramesh
B  suresh
C  satish

In [46]:
names=['ramesh','suresh','satish']
idx=['A','B','C']
cols=['Names']
pd.DataFrame(names,index=['A','B','C'],columns=['Names'])
#pd.dataframe(data,index,columns)

    Names
A  ramesh
B  suresh
C  satish

## **step-4:Add multiple columns**

In [47]:
names=['ramesh','suresh','satish']
age=[20,22,25]
pd.DataFrame(zip(names,age),index=[1,2,3],columns=['Names','Age'])

    Names  Age
1  ramesh   20
2  suresh   22
3  satish   25

## **step-5:create empty data and update the columns**

In [48]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [49]:
df=pd.DataFrame()
df['Names']=['ramesh','suresh','satish']
df['Age']=[20,22,24]
df

    Names  Age
0  ramesh   20
1  suresh   22
2  satish   24

## **step-6:add anew column with existing dataframe**

In [50]:
df=pd.DataFrame()
df['Names']=['ramesh','suresh','satish']
df['Age']=[20,22,24]
df['city']=['hyderabad','bangolore','kakinada']
df

    Names  Age       city
0  ramesh   20  hyderabad
1  suresh   22  bangolore
2  satish   24   kakinada

## **step-7:overwrite the column values**
   - I want to overwrite my age values

   - originally age is =[20,22,24]

   -  now i want to update the age=[30,32,34]

In [51]:
df['Age']=[30,32,34]
df

    Names  Age       city
0  ramesh   30  hyderabad
1  suresh   32  bangolore
2  satish   34   kakinada

In [52]:
df['age']=[30,32,34]
df

    Names  Age       city  age
0  ramesh   30  hyderabad   30
1  suresh   32  bangolore   32
2  satish   34   kakinada   34

## **step-8:Drop the column**
- labels

- axis

- index

- columns

- inplace

df.drop('age') # error
df.drop('age',axis=0) # error
df.drop('age',axis=1) # correct
# here python assume age is a label 
# python ask qn: is it index label or column
# axis=1 means columns
# axis=0 means for rows
# by default axis=0

In [53]:
df.drop('age',axis=1)
df

    Names  Age       city  age
0  ramesh   30  hyderabad   30
1  suresh   32  bangolore   32
2  satish   34   kakinada   34

In [54]:
df.drop('age',axis=1)
df        
# we are able see old columns
# because we didnot apply inplace=True

    Names  Age       city  age
0  ramesh   30  hyderabad   30
1  suresh   32  bangolore   32
2  satish   34   kakinada   34

In [55]:
# whenever we  use columns label
# no need of axis
df.drop(columns=['age'])
df

    Names  Age       city  age
0  ramesh   30  hyderabad   30
1  suresh   32  bangolore   32
2  satish   34   kakinada   34

In [56]:
df.drop(columns=['age'],inplace=True)
df

    Names  Age       city
0  ramesh   30  hyderabad
1  suresh   32  bangolore
2  satish   34   kakinada

In [57]:
df.drop(2,axis=0)
df

    Names  Age       city
0  ramesh   30  hyderabad
1  suresh   32  bangolore
2  satish   34   kakinada

In [58]:
df.drop(index=2,inplace=True)
df

    Names  Age       city
0  ramesh   30  hyderabad
1  suresh   32  bangolore

In [59]:
df = df.drop(df.index[1])
df

    Names  Age       city
0  ramesh   30  hyderabad

## **step-9:rename the columns**

mapper:dictionary {'city':'City'}
index:
columns:
axis:
copy:
inplace:

In [61]:
dict1={'city':'City'}
df.rename(dict1) # its not changing

    Names  Age       city
0  ramesh   30  hyderabad

In [62]:
dict1={'city':'City'}
df.rename(dict1,axis=1) # it's changing

    Names  Age       City
0  ramesh   30  hyderabad

In [63]:
dict1={'city':'City'}
df.rename(columns=dict1) # it's changingv

    Names  Age       City
0  ramesh   30  hyderabad

In [64]:
df

    Names  Age       city
0  ramesh   30  hyderabad

In [65]:
dict1={0:'B'}
df.rename(index=dict1)

    Names  Age       city
B  ramesh   30  hyderabad

In [124]:
df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i*i for i in range(1,10)]
df1['cube_value']=[i*i*i for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

- len

- columns

- shape

- dtypes

- head

- tail

In [125]:
df1.columns

Index(['value', 'square_value', 'cube_value'], dtype='object')

In [126]:
list(df1.columns)

['value', 'square_value', 'cube_value']

In [127]:
df1.shape

(9, 3)

In [128]:
df1.dtypes

value           int64
square_value    int64
cube_value      int64
dtype: object

In [129]:
df.dtypes

Names    object
Age       int64
city     object
dtype: object

In [130]:
df1.head()

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125

In [131]:
df1.head(2)

   value  square_value  cube_value
0      1             1           1
1      2             4           8

In [132]:
df1.tail()

   value  square_value  cube_value
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [133]:
df1.tail(2)

   value  square_value  cube_value
7      8            64         512
8      9            81         729

In [134]:
len(df1)

9

In [135]:
df1.isnull()
# we are asking a question
# python gives True or false
# true:null value not available\
# false: null value not available

   value  square_value  cube_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False

In [136]:
df1.isnull().sum()
# column wise null value count will display

value           0
square_value    0
cube_value      0
dtype: int64

In [137]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         9 non-null      int64
 1   square_value  9 non-null      int64
 2   cube_value    9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

## **step-10** 
- how to change a specific value of a column

- df1.drop

     - either it will drop column or index
 
-df1.rename

In [138]:
dictt={64:464}
df1.replace(to_replace=64,value=464,inplace=True)
df1.replace({64:464,1:111}) 
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

## **step-11:selection of a column**

In [139]:
df1['cube_value']
# series looks like dataframe only
# no rows no columns

0      1
1      8
2     27
3    464
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [140]:
df1['square_value']

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7    464
8     81
Name: square_value, dtype: int64

In [141]:
type(df1)

pandas.core.frame.DataFrame

In [142]:
 type(df1['cube_value'])

pandas.core.series.Series

In [143]:
df1[['cube_value']]

   cube_value
0           1
1           8
2          27
3         464
4         125
5         216
6         343
7         512
8         729

In [144]:
df1[['cube_value']].shape

(9, 1)

In [145]:
df1['cube_value'].shape # 1D

(9,)

In [146]:
df1.shape #2D

(9, 3)

In [147]:
df1['cube_value'].replace(64,464,inplace=True)
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

In [148]:
df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i*i for i in range(1,10)]
df1['cube_value']=[i*i*i for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [149]:
df1['cube_value'].replace(64,464,inplace=True)
df1

C:\Users\RAMYA\AppData\Local\Temp\ipykernel_24848\3343014739.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['cube_value'].replace(64,464,inplace=True)

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

## **step-12:how to apply a row**
  ###  -  loc

  ###  - iloc

##### df1.loc[rows,columns]
##### df1.iloc[rows,columns]

In [150]:
# we can select particular rows and columns using a list:[start,stop,step]

In [151]:
df1.iloc[3:7,1:3]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343

In [152]:
df1.loc[3:7,['square_value','cube_value']]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343
7            64         512

In [153]:
cols=['square_value','cube_value']
df1.loc[3:6,cols]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343

In [154]:
df1.iloc[[2,3,4]]

   value  square_value  cube_value
2      3             9          27
3      4            16         464
4      5            25         125

In [155]:
df1.iloc[[2]] # 2D dataframe

   value  square_value  cube_value
2      3             9          27

In [156]:
df1.iloc[2] #we ask only row values using one list  one dimention series

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [157]:
df1.iloc[[2,3,4],[0,2]] # it works (rows,columns) using slicing start:stop:step
# multiple always data frame will come

   value  cube_value
2      3          27
3      4         464
4      5         125

In [158]:
df1.iloc[2,0] #series

np.int64(3)

In [159]:
df1.iloc[:,0] # all the rows and fst columns #1D # series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: value, dtype: int64

In [160]:
df1.iloc[2,:]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [161]:
df1.iloc[[2],:] # 2D # dataframe

   value  square_value  cube_value
2      3             9          27

In [162]:
df1.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: value, dtype: int64

In [163]:
df1.iloc[2:6,[0]]

   value
2      3
3      4
4      5
5      6

### how to use append

In [164]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [165]:
df1.loc[9]=[10,100,1000]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [166]:
ID=len(df1)
df1.loc[ID]=[10,100,1000]
df1

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

## **step-13:save the dataframes**
#### - we can save dataframes in 2 ways 

####   - .csv
####   - .xlsx
- where i want to save :directiory

- what are the filename to save :filename

- what is the type of file: extension

- different folder:r"C:\Users\RAMYA\Documents\Naresh It\Generative AI\data1.csv"

- different folder:r"C:\Users\RAMYA\Documents\Naresh It\Generative AI\data1.xlsx"

- same folder:r"data1.csv" or r"data1.xlsx"

In [ ]:
csv_path=r"C:\Users\RAMYA\Documents\Naresh It\Generative AI\data1.csv"
df1.to_csv(csv_path)

In [ ]:
excel_path=r"C:\Users\RAMYA\Documents\Naresh It\Generative AI\data1.xlsx"
df1.to_csv(excel_path)

In [168]:
csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

In [169]:
df1

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

In [170]:
####

In [171]:
csv_path=r"data1.csv"
pd.read_csv(csv_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000

In [172]:
excel_path=r"data1.xlsx"
pd.read_excel(excel_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000

In [173]:
csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path,index=False)
df1.to_excel(excel_path,index=False)

In [174]:
csv_path=r"data1.csv"
pd.read_csv(csv_path)

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

In [175]:
excel_path=r"data1.xlsx"
pd.read_excel(excel_path)

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

In [188]:
csv_path=r"C:\Users\RAMYA\Documents\Naresh It\Generative AI\bank.csv"
df1.to_csv(csv_path)

In [194]:

csv_path = r"C:\Users\RAMYA\Documents\Naresh It\Generative AI\bank.csv"
df = pd.read_csv(csv_path)

In [195]:
df

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000